title: blog.dsoderlund.consulting
description: >-
  I write about my adventures in devops, powershell and/or sql server.
author:
  name: "David Söderlund"
  email: blog@dsoderlund.consulting
  url: "https://blog.dsoderlund.consulting"
  twitter_username: QuadmanSWE
  github_username:  QuadmanSWE
  linkedin_username: soderlunddavid
  

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

