source "https://rubygems.org"
gem "jekyll-sass-converter", "~> 2.0"
gem 'jekyll-sitemap', group: :jekyll_plugins
gem 'jekyll-seo-tag', group: :jekyll_plugins
gem 'jekyll-paginate', group: :jekyll_plugins
gem 'jekyll-spaceship', group: :jekyll_plugins
gem 'jekyll-feed', group: :jekyll_plugins